name = "JutulJUDIFilter"
uuid = "80fb201b-9edf-4eaa-a47c-dccd168d6cca"
authors = ["Grant Bruer gbruer15@gmail.com and contributors"]
version = "1.0.0-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.12"
DrWatson = "2.18"
Pkg = "1.10"
Statistics = "1.10"
julia = "1.10"
